---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:418295691381:task-definition/blue-green-task:1"
        LoadBalancerInfo:
          ContainerName: "sprinrajco"
          ContainerPort: 8080
